[AssistanceLevels]
A = 0.0 # Can only be 0 or 1
B = 0.0 # Can only be 0 or 1
Y = 0.0 # Can only be 0 or 1
X = 1.0 # Can only be 0 or 1
Bumper_Right = 0.0 # Can only be 0 or 1
Bumper_Left = 0.0 # Can only be 0 or 1
Thumb_Right = 0.0 # Can only be 0 or 1
Thumb_Left = 0.0 # Can only be 0 or 1
DirPad_X = 0.0 # Can only be 0 or 1
DirPad_Y = 0.0 # Can only be 0 or 1
Trigger_Right = 1.0 # Can only be 0 or 1
Trigger_Left = 0.0 # Can only be 0 or 1
Stick_Right_X = 1.0
Stick_Right_Y = 1.0
Stick_Left_X = 0.0
Stick_Left_Y = 0.0
Back = 0.0 # Can only be 0 or 1
Start = 0.0 # Can only be 0 or 1