[AssistanceLevels]
A = 0.0
B = 0.0
Y = 0.0
X = 0.0
Bumper_Right = 0.0
Bumper_Left = 0.0
Thumb_Right = 0.0
Thumb_Left = 0.0
DirPad_X = 0.0
DirPad_Y = 0.0
Trigger_Right = 0.0
Trigger_Left = 0.0
Stick_Right_X = 0.0
Stick_Right_Y = 0.0
Stick_Left_X = 0.0
Stick_Left_Y = 0.0
Back = 0.0
Start = 0.0