from dataclasses import dataclass
from enum import StrEnum
import time
 
class InputType(StrEnum):
    """
    Enum class representing a Type of Input in a XBOX 360 Controller
    """
    
    BTN_A = "A" # Values are {0, 1}
    BTN_B = "B" # Values are {0, 1}
    BTN_Y = "Y" # Values are {0, 1}
    BTN_X = "X" # Values are {0, 1}
    BUMPER_RIGHT = "Bumper_Right" # Values are {0, 1}
    BUMPER_LEFT = "Bumper_Left" # Values are {0, 1}
    THUMB_RIGHT = "Thumb_Right" # Values are {0, 1}
    THUMB_LEFT = "Thumb_Left" # Values are {0, 1}
    DIR_PAD_X = "DirPad_X" # Values are {-1, 0, 1}
    DIR_PAD_Y = "DirPad_Y" # Values are {-1, 0, 1}
    TRIGGER_RIGHT = "Trigger_Right" # Values are in [0, 255]
    TRIGGER_LEFT = "Trigger_Left" # Values are in [0, 255]
    STICK_RIGHT_X = "Stick_Right_X" # Values are in [-32768, 32767] 
    STICK_RIGHT_Y = "Stick_Right_Y" # Values are in [-32768, 32767] 
    STICK_LEFT_X = "Stick_Left_X" # Values are in [-32768, 32767] 
    STICK_LEFT_Y = "Stick_Left_Y" # Values are in [-32768, 32767] 
    BTN_BACK = "Back" # Values are {0, 1}
    BTN_START = "Start" # Values are {0, 1}
    
@dataclass
class ControllerInput:
    """
    ControllerInput is an input generated by an XBOX 360 Controller.
    It's composed of an Input Type and an Input Value
    """
    type : InputType
    val : int
    
        
class ControllerInputsMap:
    """
    ControllerInputsMap is a class that stores for each Input a corresponding value and timestampt of acquisition
    """
    
    def __init__(self):
        self.inputs_map = { input : (0, 0) for input in InputType }
        
    def set(self, input : ControllerInput, timestamp : float = time.time()) -> None:
        """
        Updates the value of an input
        """
        self.inputs_map[input.type] = (input.val, timestamp)
        
    def get(self, input : InputType) -> tuple[ControllerInput, float]:
        """
        Returns the ControllerInput and the timestamp of acquisition of the input
        """
        x = self.inputs_map[input]
        return ControllerInput(input, x[0]), x[1]
    
